export enum RevenueAgencies {
  ARBA = 1,
  AGIP = 2,
  ATER = 3,
  ATP = 4,
  ATM = 5,
  API = 6,
  AREF = 7,
  ASIP = 8,
  AGENCIA_RECAUDACION_TRIBUTARIA = 9,
  DGR_LA_PAMPA = 10,
  DGIP_LA_RIOJA = 11,
  DGR_MISIONES = 12,
  DPR_NEUQUEN = 13,
  DGR_SALTA = 14,
  DGR_CHUBUT = 15,
  DGR_CORDOBA = 16,
  DGR_CORRIENTES = 17,
  DGR_FORMOSA = 18,
  DGR_SAN_JUAN = 19,
  DGR_TUCUMAN = 20,
  DGR_SANTIAGO_DEL_ESTERO = 21,
  RENTAS_JUJUY = 22,
  RENTAS_SAN_LUIS = 23,
}

export const statesValues: Record<string, number> = {
  'Provincia de Buenos Aires': 1,
  'Ciudad Autónoma de Buenos Aires': 2,
  'Entre Ríos': 3,
  Chaco: 4,
  Mendoza: 5,
  'Santa Fe': 6,
  'Tierra del Fuego': 7,
  'Santa Cruz': 8,
  'Rio Negro': 9,
  'La Pampa': 10,
  'La Rioja': 11,
  Misiones: 12,
  Neuquén: 13,
  Salta: 14,
  Chubut: 15,
  Córdoba: 16,
  Corrientes: 17,
  Formosa: 18,
  'San Juan': 19,
  Tucumán: 20,
  'Santiago del Estero': 21,
  Jujuy: 22,
  'San Luis': 23,
};

export enum Currency {
  ARS = '$',
  USD = 'USD',
  EUR = '€',
  GBP = '£',
  CNY = '¥',
  BTC = '₿',
  ETH = 'Ξ',
  LTC = 'Ł',
}

export enum IIBBStatus {
  UNIFIED = 'Unified',
  GENERAL = 'General',
}
